In [1]:
# importacion general de librerias y de visualizacion (matplotlib y seaborn)
!pip3 install pandas
!pip3 install matplotlib
!pip3 install seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

plt.style.use('default') # haciendo los graficos un poco mas bonitos en matplotlib
#plt.rcParams['figure.figsize'] = (20, 10)

sns.set(style="whitegrid") # seteando tipo de grid en seaborn

pd.options.display.float_format = '{:20,.2f}'.format # suprimimos la notacion cientifica en los outputs

import warnings
warnings.filterwarnings('ignore')

In [2]:
!pip3 install nltk
!pip3 install sklearn
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import random
import numpy as np
import matplotlib.pyplot as plt

In [3]:
contents=pd.read_csv('contents_text_sample.csv')

In [4]:
contents.head()

id          title                                               text
0   50  Anacardiaceae  {{Ficha de taxón\n| name = Anacardiáceas\n| im...
1   62  Antipartícula  [[Archivo:Materia antimateria.png|thumb|200px|...
2   78   Año bisiesto  '''Año bisiesto''' es una expresión que deriva...
3  127          Avena  {{otros usos|Avena sativa|la avena común}}\n{{...
4  160       Alfabeto  {{distinguir|analfabeto|alfabetización}} \n[[A...

In [5]:
contents["text"].isnull().value_counts()

False    206600
True          7
Name: text, dtype: int64

In [6]:
contents = contents.dropna()

In [7]:
texts = []

In [8]:
for line in contents["text"]:
    if len(texts)%100000==0:
        print(len(texts))
    texts.append(line)

0
100000
200000


In [9]:
len(texts)

206600

In [10]:
nltk.download('punkt')
text = random.choice(texts)
text, nltk.word_tokenize(text)

[nltk_data] Downloading package punkt to /home/marconcz/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


('{{commonscat|Festivals of the Netherlands}}\n\n[[Categoría:Festivales por país|Paises Bajos]]\n[[Categoría:Cultura de los Países Bajos]]\n[[Categoría:Eventos en los Países Bajos]]',
 ['{',
  '{',
  'commonscat|Festivals',
  'of',
  'the',
  'Netherlands',
  '}',
  '}',
  '[',
  '[',
  'Categoría',
  ':',
  'Festivales',
  'por',
  'país|Paises',
  'Bajos',
  ']',
  ']',
  '[',
  '[',
  'Categoría',
  ':',
  'Cultura',
  'de',
  'los',
  'Países',
  'Bajos',
  ']',
  ']',
  '[',
  '[',
  'Categoría',
  ':',
  'Eventos',
  'en',
  'los',
  'Países',
  'Bajos',
  ']',
  ']'])

In [11]:
nltk.download('stopwords')
nltk.corpus.stopwords.words('spanish')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/marconcz/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni',
 'contra',
 'otros',
 'ese',
 'eso',
 'ante',
 'ellos',
 'e',
 'esto',
 'mí',
 'antes',
 'algunos',
 'qué',
 'unos',
 'yo',
 'otro',
 'otras',
 'otra',
 'él',
 'tanto',
 'esa',
 'estos',
 'mucho',
 'quienes',
 'nada',
 'muchos',
 'cual',
 'poco',
 'ella',
 'estar',
 'estas',
 'algunas',
 'algo',
 'nosotros',
 'mi',
 'mis',
 'tú',
 'te',
 'ti',
 'tu',
 'tus',
 'ellas',
 'nosotras',
 'vosotros',
 'vosotras',
 'os',
 'mío',
 'mía',
 'míos',
 'mías',
 'tuyo',
 'tuya',
 'tuyos',
 'tuyas',
 'suyo',
 'suya',
 'suyos',
 'suyas',
 'nuestro',
 'nuestra',
 'nuestros',
 'nuestras',
 'vuestro'

In [12]:
vectorizer = CountVectorizer(lowercase=True, stop_words=nltk.corpus.stopwords.words('spanish'))

In [13]:
matrix = vectorizer.fit_transform(texts)

In [14]:
len(vectorizer.vocabulary_)

1873406

In [15]:
matrix.shape[0]

206600

In [16]:
matrix.shape

(206600, 1873406)

In [17]:
np.argmax(np.asarray(matrix.sum(axis=1).flatten())[0])

191069

In [18]:
np.asarray(matrix.sum(axis=0))[0]

array([27816, 33889,   191, ...,     1,     1,     1])

In [19]:
coso = np.asarray(matrix.sum(axis=0))[0]
coso

array([27816, 33889,   191, ...,     1,     1,     1])

In [20]:
proba = (coso/coso.sum())

In [21]:
proba

array([4.19167517e-04, 5.10683347e-04, 2.87823539e-06, ...,
       1.50692953e-08, 1.50692953e-08, 1.50692953e-08])

In [22]:
acum = 0
for x in proba:
    acum = acum + (- np.log2(x))*x

In [23]:
acum

13.974710728546325

In [24]:
matriz = np.matrix([[11.0,12,13],
                      [21,22,23],
                      [31,32,33]])

In [25]:
proba.shape[0] == matrix.shape[1]

True

In [26]:
for i in range(0,matriz.shape[1]):
    denominador = matriz.sum(axis=1)[i]
    matriz[i] = matriz[i]/denominador

In [27]:
matriz

matrix([[0.30555556, 0.33333333, 0.36111111],
        [0.31818182, 0.33333333, 0.34848485],
        [0.32291667, 0.33333333, 0.34375   ]])

In [ ]:
for i in range(0,matrix.shape[1]):
    denom = matrix.sum(axis=1)[i]
    matrix[i] = matrix[i]/denom
    if (i%1000==0):
        print(i)


0


In [ ]:
matriz